version: "3"
services:
    hdsearch:
      cpuset: 1-6
      image: mklean/baseline-microsuite:hdsearch_router_setalgebra
      stdin_open: true # docker run -i
      tty: true        # docker run -t
      ports:
          - "50050:50050"
          - "50051:50051"
          - "50052:50052"
          - "50053:50053"
          - "50054:50054"
          - "50055:50055"
          - "11211:11211"
