- name: 'vanilla'
  config:
      pstate: True
      c1: '2_2'
      c1e: '10_20'
      c6: True
  kernel: '4.15.0-159-generic'
  grub:
      menuentry: '1>6'
      boot_options: 'isolcpus=3 irqaffinity=0,1,2,4,5,6,7,8,9 rcu_nocbs=3 nohz=on'
- name: 'baseline'
  config:
      pstate: False
      c1: '2_2'
      c1e: '10_20'
      c6: True
  kernel: '4.15.18-c1-2-2-c1e-10-20'
  grub:
      menuentry: '1>0'
      boot_options: 'intel_pstate=disable isolcpus=3 irqaffinity=0,1,2,4,5,6,7,8,9 rcu_nocbs=3 nohz=on'
- name: 'disable_cstates'
  config:
      pstate: False
      c1: False
      c1e: False
      c6: False
  kernel: '4.15.18-c1-2-2-c1e-10-20'
  grub:      
      menuentry: '1>0'
      boot_options: 'intel_pstate=disable intel_idle.max_cstate=0 idle=poll isolcpus=3 irqaffinity=0,1,2,4,5,6,7,8,9 rcu_nocbs=3 nohz=on'
- name: 'disable_c6'
  config:
      pstate: False
      c1: '2_2'
      c1e: '10_20'
      c6: False
  kernel: '4.15.18-c1-2-2-c1e-10-20'
  grub:      
      menuentry: '1>0'
      boot_options: 'intel_pstate=disable intel_idle.max_cstate=2 isolcpus=3 irqaffinity=0,1,2,4,5,6,7,8,9 rcu_nocbs=3 nohz=on'
- name: 'disable_c1e_c6'
  config:
      pstate: False
      c1: '2_2'
      c1e: False
      c6: False
  kernel: '4.15.18-c1-2-2-c1e-10-20'
  grub:      
      menuentry: '1>0'
      boot_options: 'intel_pstate=disable intel_idle.max_cstate=1 isolcpus=3 irqaffinity=0,1,2,4,5,6,7,8,9 rcu_nocbs=3 nohz=on'
- name: 'quick_c1'
  config:
      pstate: False
      c1: '1_1'
      c1e: '10_20'
      c6: True
  kernel: '4.15.18-c1-1-1-c1e-10-20'
  grub:      
      menuentry: '1>2'
      boot_options: 'intel_pstate=disable isolcpus=3 irqaffinity=0,1,2,4,5,6,7,8,9 rcu_nocbs=3 nohz=on'
- name: 'quick_c1_disable_c6'
  config:
      pstate: False
      c1: '1_1'
      c1e: '10_20'
      c6: False
  kernel: '4.15.18-c1-1-1-c1e-10-20'
  grub:      
      menuentry: '1>2'
      boot_options: 'intel_pstate=disable intel_idle.max_cstate=2 isolcpus=3 irqaffinity=0,1,2,4,5,6,7,8,9 rcu_nocbs=3 nohz=on'
- name: 'quick_c1_c1e'
  config:
      pstate: False
      c1: '1_1'
      c1e: '5_20'
      c6: True
  kernel: '4.15.18-c1-1-1-c1e-05-20'
  grub:      
      menuentry: '1>4'
      boot_options: 'intel_pstate=disable isolcpus=3 irqaffinity=0,1,2,4,5,6,7,8,9 rcu_nocbs=3 nohz=on'
