---
- name: Install Setalgebra
  hosts: midtier
  tasks:    
  - name: Install SetAlgebra if not exists
    unarchive: 
      src: ~/SetAlgebra.tgz 
      dest: ~/
  - name: Set Up Docker Curl
    command: ~/SetAlgebra/scripts/set-up-docker.sh
  - name: Make Space to Commit Image
    command: ~/SetAlgebra/scripts/change-storage-location-docker.sh

- name: Execute SetAlgebra Container 
  hosts:
  - midtier
  #- bucket
  #- client
  tags: compose_up_setalgebra
  tasks:
    - name: Change to docker group 
      command: sudo newgrp docker
    
    - name: Compose Up SetAlgebra
      command: ~/SetAlgebra/scripts/docker-compose-up.sh
